# Generated by Django 3.0.3 on 2020-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='selldetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
