# Generated by Django 3.0.3 on 2020-04-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0005_auto_20200422_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='limit',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
