# Generated by Django 3.0.3 on 2020-04-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0006_customer_limit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
